FROM alpine:3.22
# docker build -f Dockerfile.alpine-3.22.build -t otx-3rd-libs:alpine-3.22 .

# Install build tools
RUN apk add --no-cache \
    build-base \
    cmake \
    git \
    icu-dev \
    perl \
    readline-dev \
    linux-headers

ARG ABSEIL_VERSION=20240722.0
ARG PROTOBUF_VERSION=5.29.3
ARG GRPC_VERSION=1.71.0
ARG POCO_VERSION=1.9.4
ARG XERCES_VERSION=3.2.4
ARG XQILLA_VERSION=2.3.4
ARG OPENSSL_VERSION=3.4.1
ARG BOOST_VERSION=1.87.0
ENV LUA_VERSION=5.3.5
ARG JSONCONS_VERSION=1.0.0
ARG RAPIDJSON_VERSION=1.1.0
ARG ASIO_VERSION=1.28.2

ENV BUILD_CXX_STANDARD=20

ENV ABSEIL_ROOT=/opt/abseil
ENV PROTOBUF_ROOT=/opt/protobuf
ENV GRPC_ROOT=/opt/grpc
ENV POCO_ROOT=/opt/poco
ENV XERCESC_ROOT=/opt/xerces-c
ENV XQILLA_ROOT=/opt/xqilla
ENV OPENSSL_ROOT=/opt/openssl
ENV BOOST_ROOT=/opt/boost
ENV LUA_ROOT=/opt/lua
ENV JSONCONS_ROOT=/opt/jsoncons
ENV RAPIDJSON_ROOT=/opt/rapidjson
ENV ASIO_ROOT=/opt/asio

WORKDIR /sources
RUN echo    "============================================================================ " \
	&& echo "========================= Building abseil-cpp =============================== " \
	&& echo "============================================================================ " \
	&& git clone \
	   --depth 1 \
	   -b ${ABSEIL_VERSION} \
	   https://github.com/abseil/abseil-cpp.git \
	&& mkdir -p abseil-cpp/build \
	&& cd abseil-cpp/build \
	&& cmake -G "Unix Makefiles" \
	   -DCMAKE_BUILD_TYPE=Release \
	   -DCMAKE_CXX_STANDARD=$BUILD_CXX_STANDARD \
	   -DCMAKE_POSITION_INDEPENDENT_CODE=ON \
	   -DBUILD_SHARED_LIBS=OFF \
	   -DBUILD_TESTING=OFF \
	   -DABSL_PROPAGATE_CXX_STD=ON \
	   -DABSL_ENABLE_INSTALL=ON \
	   -DCMAKE_INSTALL_PREFIX=$ABSEIL_ROOT \
	   /sources/abseil-cpp \
	&& make -j8 \
	&& make install \
	&& ln -s "$ABSEIL_ROOT/lib64" "$ABSEIL_ROOT/lib" \
	&& rm -rf /sources/abseil-cpp

WORKDIR /sources
RUN echo    "============================================================================ " \
	&& echo "========================= Building google protobuf ========================= " \
	&& echo "============================================================================ " \
	&& git clone \
	   -b v${PROTOBUF_VERSION} \
	   --recurse-submodules \
	   https://github.com/protocolbuffers/protobuf.git \
	&& mkdir -p protobuf/build \
	&& cd protobuf/build \
	&& cmake -G "Unix Makefiles" \
	   -DCMAKE_POSITION_INDEPENDENT_CODE=ON \
	   -DCMAKE_BUILD_TYPE=Release \
	   -DBUILD_SHARED_LIBS=OFF \
	   -Dprotobuf_BUILD_SHARED_LIBS=OFF \
	   -Dprotobuf_MSVC_STATIC_RUNTIME=OFF \
	   -Dprotobuf_BUILD_TESTS=OFF \
	   -Dprotobuf_BUILD_CONFORMANCE=OFF \
	   -Dprotobuf_BUILD_EXAMPLES=OFF \
	   -Dprotobuf_BUILD_PROTOC_BINARIES=ON \
	   -Dprotobuf_WITH_ZLIB=OFF \
	   -Dprotobuf_VERBOSE=OFF \
	   -Dprotobuf_ABSL_PROVIDER=package \
	   -Dabsl_DIR=$ABSEIL_ROOT/lib/cmake/absl \
	   -DCMAKE_CXX_STANDARD=$BUILD_CXX_STANDARD \
	   -DCMAKE_PREFIX_PATH=$PROTOBUF_ROOT \
	   -DCMAKE_INSTALL_PREFIX=$PROTOBUF_ROOT \
	   /sources/protobuf \
	&& make -j8 \
	&& make install \
	&& ln -s "$PROTOBUF_ROOT/lib64" "$PROTOBUF_ROOT/lib" \
	&& rm -rf /sources/protobuf

WORKDIR /sources
RUN echo    "============================================================================ " \
	&& echo "========================= Building poco ==================================== " \
	&& echo "============================================================================ " \
	&& git clone \
	   --depth 1 \
	   -b poco-${POCO_VERSION}-release \
	   https://github.com/pocoproject/poco.git \
	&& mkdir -p poco/build \
	&& cd poco/build \
	&& cmake -G "Unix Makefiles" \
	   -DCMAKE_BUILD_TYPE=Release \
	   -DCMAKE_CXX_FLAGS="-std=c++$BUILD_CXX_STANDARD" \
	   -DCMAKE_CXX_STANDARD=$BUILD_CXX_STANDARD \
	   -DPOCO_STATIC=ON \
	   -DBUILD_SHARED_LIBS=OFF \
	   -DENABLE_ENCODINGS=OFF \
	   -DENABLE_ENCODINGS_COMPILER=OFF \
	   -DENABLE_JSON=OFF \
	   -DENABLE_MONGODB=OFF \
	   -DENABLE_REDIS=OFF \
	   -DENABLE_PDF=OFF \
	   -DENABLE_NET=OFF \
	   -DENABLE_NETSSL=OFF \
	   -DENABLE_NETSSL_WIN=OFF \
	   -DENABLE_CRYPTO=OFF \
	   -DENABLE_DATA=OFF \
	   -DENABLE_DATA_SQLITE=OFF \
	   -DENABLE_DATA_MYSQL=OFF \
	   -DENABLE_DATA_ODBC=OFF \
	   -DENABLE_SEVENZIP=OFF \
	   -DENABLE_APACHECONNECTOR=OFF \
	   -DENABLE_CPPPARSER=OFF \
	   -DENABLE_POCODOC=OFF \
	   -DENABLE_PAGECOMPILER=OFF \
	   -DENABLE_PAGECOMPILER_FILE2PAGE=OFF \
	   -DFORCE_OPENSSL=OFF \
	   -DENABLE_TESTS=OFF \
	   -DPOCO_UNBUNDLED=OFF \
	   -DPOCO_MT=OFF \
	   -DENABLE_MSVC_MP=OFF \
	   -DENABLE_XML=ON \
	   -DENABLE_UTIL=ON \
	   -DENABLE_ZIP=ON \
	   -DCMAKE_INSTALL_PREFIX=$POCO_ROOT \
	   /sources/poco \
	&& make -j8 \
	&& make install \
	&& ln -s "$POCO_ROOT/lib64" "$POCO_ROOT/lib" \
	&& rm -rf /sources/poco
	
WORKDIR /sources
RUN echo    "============================================================================ " \
	&& echo "========================= Building xerces-c ================================ " \
	&& echo "============================================================================ " \
	&& git clone \
	   --depth 1 \
	   -b v${XERCES_VERSION} \
	   https://github.com/apache/xerces-c.git \
	&& mkdir -p xerces-c/build \
	&& cd xerces-c/build \
	&& cmake -G "Unix Makefiles" \
	   -DCMAKE_CXX_STANDARD=$BUILD_CXX_STANDARD \
	   -DCMAKE_BUILD_TYPE=Release \
	   -DBUILD_SHARED_LIBS=OFF \
	   -DCMAKE_POSITION_INDEPENDENT_CODE=ON \
	   -Dtranscoder=iconv \
	   -DCMAKE_INSTALL_PREFIX=$XERCESC_ROOT \
	   /sources/xerces-c \
	&& make -j8 \
	&& make install \
	&& ln -s "$XERCESC_ROOT/lib64" "$XERCESC_ROOT/lib" \
	&& rm -rf /sources/xerces-c
	
WORKDIR /sources
COPY scripts/patch-xqilla.alpine.sh /tmp/patch-xqilla.sh
RUN echo    "============================================================================ " \
	&& echo "========================= Building xqilla ================================== " \
	&& echo "============================================================================ " \
	&& wget https://sourceforge.net/projects/xqilla/files/XQilla-${XQILLA_VERSION}.tar.gz \
	&& tar -xzvf XQilla-${XQILLA_VERSION}.tar.gz \
	&& chmod +x /tmp/patch-xqilla.sh \
	&& /tmp/patch-xqilla.sh \
	&& mkdir -p XQilla-${XQILLA_VERSION}/build \
	&& cd XQilla-${XQILLA_VERSION}/build \
	&& /sources/XQilla-${XQILLA_VERSION}/configure \
	   CXXFLAGS="-fPIC -std=c++$BUILD_CXX_STANDARD" \
	   --disable-shared \
	   --enable-static \
	   --with-xerces=$XERCESC_ROOT \
	   --prefix=$XQILLA_ROOT \
	&& make -j8 \
	&& make install \
	&& rm -rf /sources/XQilla-${XQILLA_VERSION} /sources/XQilla-${XQILLA_VERSION}.tar.gz
	
WORKDIR /sources
RUN echo    "============================================================================ " \
	&& echo "========================= Building openssl ================================= " \
	&& echo "============================================================================ " \
	&& git clone \
	   --depth 1 \
	   -b openssl-${OPENSSL_VERSION} \
	   https://github.com/openssl/openssl.git \
	&& cd openssl \
	&& perl /sources/openssl/Configure \
	   no-shared \
	   enable-static-engine \
	   --prefix=$OPENSSL_ROOT \
	   --openssldir=$OPENSSL_ROOT \
	&& make -j8 \
	&& make install \
	&& ln -s "$OPENSSL_ROOT/lib64" "$OPENSSL_ROOT/lib" \
	&& rm -rf /sources/openssl
	
WORKDIR /sources
RUN echo    "============================================================================ " \
	&& echo "========================= Building boost =================================== " \
	&& echo "============================================================================ " \
	&& BOOST_VERSION_UNDERSCORE=$(echo "$BOOST_VERSION" | tr '.' '_') \
    && wget https://archives.boost.io/release/${BOOST_VERSION}/source/boost_${BOOST_VERSION_UNDERSCORE}.tar.gz \
    && tar -xzvf boost_${BOOST_VERSION_UNDERSCORE}.tar.gz \
    && cd boost_${BOOST_VERSION_UNDERSCORE} \
    && ./bootstrap.sh \
    && ./b2 \
	   boost.locale.icu=off \
	   install \
	   link=static \
	   variant=release \
	   threading=multi \
	   cxxflags="-fPIC -std=c++$BUILD_CXX_STANDARD" \
	   address-model=64 \
	   architecture=x86 \
	   --prefix=$BOOST_ROOT \
	   -j8 \
    && rm -rf /sources/boost_${BOOST_VERSION_UNDERSCORE} /sources/boost_${BOOST_VERSION_UNDERSCORE}.tar.gz
	
WORKDIR /sources
RUN echo    "============================================================================ " \
	&& echo "========================= Building lua ================================== " \
	&& echo "============================================================================ " \
	&& wget https://www.lua.org/ftp/lua-${LUA_VERSION}.tar.gz \
	&& tar -xzvf lua-${LUA_VERSION}.tar.gz \
	&& cd lua-${LUA_VERSION} \
	&& make -C src liblua.a \
	&& echo "" > src/lua \
	&& echo "" > src/luac \
	&& make INSTALL_TOP=$LUA_ROOT install \
	&& rm -rf /sources/lua-${LUA_VERSION} /sources/lua-${LUA_VERSION}.tar.gz

WORKDIR /sources
RUN echo    "============================================================================ " \
	&& echo "========================= Building jsoncons ================================ " \
	&& echo "============================================================================ " \
 	&& git clone \
 	   --depth 1 \
 	   -b v${JSONCONS_VERSION} \
 	   https://github.com/danielaparker/jsoncons.git \
 	&& mkdir -p jsoncons/build \
 	&& cd jsoncons/build \
 	&& cmake -G "Unix Makefiles" \
	   -DCMAKE_BUILD_TYPE=Release \
	   -DJSONCONS_BUILD_TESTS=Off \
	   -DCMAKE_INSTALL_PREFIX=$JSONCONS_ROOT \
	   /sources/jsoncons \
 	&& make -j8 \
 	&& make install \
	&& ln -s "$JSONCONS_ROOT/lib64" "$JSONCONS_ROOT/lib" \
    && rm -rf /sources/jsoncons

WORKDIR /sources
RUN echo    "============================================================================ " \
	&& echo "========================= Building rapidjson =============================== " \
	&& echo "============================================================================ " \
 	&& git clone \
 	   --depth 1 \
 	   -b v${RAPIDJSON_VERSION} \
 	   https://github.com/Tencent/rapidjson.git \
 	&& mkdir -p ${RAPIDJSON_ROOT} \
 	&& cp -r /sources/rapidjson/include ${RAPIDJSON_ROOT}/include \
    && rm -rf /sources/rapidjson

WORKDIR /sources
RUN echo    "============================================================================ " \
	&& echo "========================= Building asio =============================== " \
	&& echo "============================================================================ " \
	&& ASIO_VERSION_UNDERSCORE=$(echo "$ASIO_VERSION" | tr '.' '-') \
 	&& git clone \
 	   --depth 1 \
 	   -b asio-${ASIO_VERSION_UNDERSCORE} \
 	   https://github.com/chriskohlhoff/asio.git \
 	&& mkdir -p ${ASIO_ROOT} \
 	&& cp -r /sources/asio/asio/include ${ASIO_ROOT}/include \
    && rm -rf /sources/asio

WORKDIR /sources
RUN echo    "============================================================================ " \
	&& echo "========================= Cloning grpc ======================================= " \
	&& echo "============================================================================ " \
	&& git clone \
	   --depth 1 \
	   -b v${GRPC_VERSION} \
	   --recurse-submodules \
	   https://github.com/grpc/grpc.git

WORKDIR /sources
RUN echo    "============================================================================ " \
	&& echo "========================= Building grpc ===================================== " \
	&& echo "============================================================================ " \
	&& mkdir -p grpc/build \
	&& cd grpc/build \
	&& cmake -G "Unix Makefiles" \
	   -DCMAKE_BUILD_TYPE=Release \
	   -DCMAKE_CXX_STANDARD=$BUILD_CXX_STANDARD \
	   -DCMAKE_POSITION_INDEPENDENT_CODE=ON \
	   -DBUILD_SHARED_LIBS=OFF \
	   -DgRPC_INSTALL=ON \
	   -DgRPC_BUILD_TESTS=OFF \
	   -DgRPC_BUILD_CSHARP_EXT=OFF \
	   -DgRPC_BUILD_GRPC_CPP_PLUGIN=ON \
	   -DgRPC_BUILD_CODEGEN=ON \
	   -DgRPC_ABSL_PROVIDER=package \
	   -DgRPC_PROTOBUF_PROVIDER=package \
	   -DgRPC_SSL_PROVIDER=package \
	   -DgRPC_ZLIB_PROVIDER=module \
	   -DgRPC_CARES_PROVIDER=module \
	   -DgRPC_RE2_PROVIDER=module \
	   -DRE2_BUILD_TESTING=OFF \
	   -Dabsl_DIR=$ABSEIL_ROOT/lib/cmake/absl \
	   -DProtobuf_DIR=$PROTOBUF_ROOT/lib/cmake/protobuf \
	   -Dutf8_range_DIR=$PROTOBUF_ROOT/lib/cmake/utf8_range \
	   -DOPENSSL_ROOT_DIR=$OPENSSL_ROOT \
	   -DCMAKE_INSTALL_PREFIX=$GRPC_ROOT \
	   /sources/grpc \
	&& make -j8 \
	&& make install \
	&& ln -s "$GRPC_ROOT/lib64" "$GRPC_ROOT/lib" \
	&& rm -rf /sources/grpc

WORKDIR /opt
RUN ls -l

# Default command
CMD ["/bin/sh"]