services:
  # docker compose run --rm builder-ubi9
  builder-ubi9:
    platform: linux/amd64
    container_name: otx-rt-builder-redhat-1
    image: otx-3rd-libs:ubi9
    volumes:
      - /mnt/i/work/Issues/18990/Cpp/:/otx-rt
      - ../.build/redhat-ubi9/otx-rt:/build/otx-rt
      - ../.output/redhat-ubi9/include/:/build/include
      - ../.output/redhat-ubi9/bin/:/build/bin
    working_dir: /build
    command: >
      sh -c '
        echo "============================================================================ " &&
        echo "========================= Creating toolchain.cmake ========================= " &&
        echo "============================================================================ " &&
        echo "set(CMAKE_SYSTEM_NAME redhat)"      >  /toolchain.cmake &&
        echo "set(CMAKE_SYSTEM_PROCESSOR x86_64)" >> /toolchain.cmake &&
        echo "set(CMAKE_C_COMPILER gcc)"          >> /toolchain.cmake &&
        echo "set(CMAKE_CXX_COMPILER g++)"        >> /toolchain.cmake &&
        cat  /toolchain.cmake &&
        echo "============================================================================ " &&
        echo "========================= Building otx-rt ================================== " &&
        echo "============================================================================ " &&
        mkdir -p /build/otx-rt &&
        cd /build/otx-rt &&
        cmake -G "Unix Makefiles" \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_CXX_STANDARD=$$BUILD_CXX_STANDARD \
            -DCMAKE_TOOLCHAIN_FILE=/toolchain.cmake \
            -DOtxDiagManagerSourceDir=/build/otx-diagmanager/lib \
            -DOtxDiagManagerPath=/build/otx-diagmanager/bin \
            -DMCDKERNEL_LIBRARY_DIR=/opt/vw/lib \
            -DRT7_BUILD_STATIC_LIBS=ON \
            -DCPP_BUILD_TYPE="x64" \
            -DRt7InstallDir=/build/otx-rt/binaries/ \
            -DASIO_ROOT=$$ASIO_ROOT \
            -DBOOST_ROOT=$$BOOST_ROOT -DBoost_USE_STATIC_LIBS=ON \
            -DPoco_ROOT=$$POCO_ROOT \
            -DProtobuf_ROOT=$$PROTOBUF_ROOT \
            -DOPENSSL_ROOT_DIR=$$OPENSSL_ROOT \
            -DLUA_ROOT=$$LUA_ROOT \
            -DXercesC_ROOT=$$XERCESC_ROOT \
            -DXQilla_ROOT=$$XQILLA_ROOT \
            -DRAPIDJSON_ROOT=$$RAPIDJSON_ROOT \
            -DJSONCONS_ROOT=$$JSONCONS_ROOT \
            /otx-rt &&
        make -j8 &&
        cp -a /build/otx-rt/bin/. /build/bin/ &&
        cp -a /build/otx-rt/bin/include/. /build/include/
      '
    stdin_open: true
    tty: true